### ISSUE TITLE
Parameter TO produces a bug in swift-mailer

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [marvinrabe/dokuwiki-contact#4]
Hi,

for my purpose the plugin would be great if it would support variable email destinations (with multiple email addresses). Therefore I've tested the plugin with the "to" parameter. But I don't understand how to use this parameter. I've tried the following:
```
{{contact>to=vorname.nachname@firma.de}}
```
But this brings up a swift-mailer error. Is it supported by the plugin? What can I do?

Regards
Juergen

**Comment by marvinrabe** [comment]
Hello Jürgen,

the to parameter should be used with a username. It will send emails to the email address of the user. There is currently no way to enter a email address directly. But hey: Its open source! Feel free to extend this plugin to your liking ;-)

Sincerely
Marvin

**Comment by Juergen-aus-Koeln** [comment]
Thank you. Now the syntax of the parameter is clear for me. 
Perhaps I'll try to enlarge the plugin, but I'm no programmer.

Regards
Jürgen
